//! Redesigned shell tool inspired by Claude Code's Bash tool.
//!
//! Key improvements over the original `ShellExecTool`:
//! - **Command strings**: Interface is `"command": "ls -la"` via `bash -c`
//! - **Persistent cwd**: Working directory persists across calls
//! - **Output truncation**: 30KB max with head+tail line preservation
//! - **Background execution**: `run_in_background: true` spawns a task
//! - **Timeouts**: 120s default, 600s max, configurable via `timeout_ms`
//! - **Security**: env_clear, secret env vars, command denylist,
//!   Landlock filesystem sandboxing on Linux 5.13+
//!
//! The legacy `argv` mode has been removed. All commands go through `bash -c`
//! which ensures the denylist and security checks apply uniformly.

pub mod background;
pub mod classification;
pub mod exec;
pub mod output;
pub mod permissions;
pub mod security;
pub mod types;

use crate::{SandboxError, Tool, error::SandboxResult};
use alms_core::config::{ShellClassificationMode as CoreClassificationMode, ShellPermissions};
use classification::ClassificationMode;
use exec::command_excerpt;
use permissions::CompiledPermissions;
use serde_json::Value;
use std::collections::HashMap;
use std::path::PathBuf;
use tracing::{error, warn};
use types::{DEFAULT_TIMEOUT_MS, MAX_TIMEOUT_MS, ShellInput, ShellState};
use uuid::Uuid;

/// Build the per-`ShellTool` PWD marker.
///
/// The marker is generated once at tool construction and embedded in every
/// command this `ShellTool` runs. Earlier versions used a fixed `__ALMS_PWD_MARKER__`
/// constant — if a user script ever printed that exact string, it would
/// corrupt cwd tracking. The per-instance UUID nonce avoids that class of
/// collision: even if a script intentionally tries to forge the marker, it
/// cannot guess the random suffix. Cloning a `ShellTool` (e.g. when the
/// runtime registers the same tool under both `shell` and `shell_exec`)
/// preserves the marker so cwd recovery semantics remain consistent.
fn new_pwd_marker() -> String {
    format!("__ALMS_PWD_{}__", Uuid::new_v4().simple())
}

/// The tool name used for registration. Agents call it as `"shell"`.
pub const SHELL_TOOL_NAME: &str = "shell";

/// Legacy alias for backward compatibility.
pub const SHELL_TOOL_ALIAS: &str = "shell_exec";

/// Redesigned shell tool with persistent cwd, command strings, and
/// background execution support.
///
/// Replaces the original `ShellExecTool`. Registered under the name `"shell"`
/// with `"shell_exec"` as a backward-compatible alias.
#[derive(Debug)]
pub struct ShellTool {
    /// When Some, cwd is validated against this root in sandboxed mode.
    sandbox_root: Option<PathBuf>,
    /// When true, no cwd restriction is applied.
    unrestricted: bool,
    /// Default environment variables injected into spawned processes.
    default_env: HashMap<String, String>,
    /// Persistent shell state (cwd tracking, background tasks).
    state: ShellState,
    /// Compiled permission rules (allow/deny patterns for commands).
    permissions: CompiledPermissions,
    /// Built-in classifier policy (enforced after the permission check).
    classification_mode: ClassificationMode,
    /// Per-instance random PWD marker (generated by [`new_pwd_marker`]).
    /// Used to delimit the appended `pwd` output so we can recover the cwd
    /// across calls without colliding with arbitrary user-script output.
    pwd_marker: String,
}

/// Convert the serde-owned enum in `alms-core` into the internal sandbox
/// enum. Keeping two types avoids pulling `serde` into the hot path and lets
/// the sandbox crate extend its modes without breaking the config wire format.
fn map_classification_mode(m: CoreClassificationMode) -> ClassificationMode {
    match m {
        CoreClassificationMode::Off => ClassificationMode::Off,
        CoreClassificationMode::Warn => ClassificationMode::Warn,
        CoreClassificationMode::BlockDestructive => ClassificationMode::BlockDestructive,
        CoreClassificationMode::Strict => ClassificationMode::Strict,
    }
}

impl Clone for ShellTool {
    fn clone(&self) -> Self {
        // ShellState uses Arc internally, so cloning shares the state.
        // The pwd_marker is preserved so cloned instances (e.g. the
        // `shell_exec` alias registered alongside `shell`) recover the cwd
        // through the same marker the parent emitted.
        Self {
            sandbox_root: self.sandbox_root.clone(),
            unrestricted: self.unrestricted,
            default_env: self.default_env.clone(),
            state: self.state.clone(),
            permissions: self.permissions.clone(),
            classification_mode: self.classification_mode,
            pwd_marker: self.pwd_marker.clone(),
        }
    }
}

impl Default for ShellTool {
    fn default() -> Self {
        Self {
            sandbox_root: None,
            unrestricted: true,
            default_env: HashMap::new(),
            state: ShellState::new(std::env::current_dir().unwrap_or_else(|_| PathBuf::from("."))),
            permissions: CompiledPermissions::compile(&ShellPermissions::default()),
            classification_mode: ClassificationMode::default(),
            pwd_marker: new_pwd_marker(),
        }
    }
}

impl ShellTool {
    /// Create an unrestricted shell tool.
    pub fn new() -> Self {
        Self::default()
    }

    /// Create a sandboxed shell tool. The cwd is restricted to `root`.
    pub fn sandboxed(root: PathBuf) -> Self {
        let state = ShellState::new(root.clone());
        Self {
            sandbox_root: Some(root),
            unrestricted: false,
            default_env: HashMap::new(),
            state,
            permissions: CompiledPermissions::compile(&ShellPermissions::default()),
            classification_mode: ClassificationMode::default(),
            pwd_marker: new_pwd_marker(),
        }
    }

    /// Create with explicit policy (matching the old `ShellExecTool::with_policy`).
    pub fn with_policy(sandbox_root: Option<PathBuf>, unrestricted: bool) -> Self {
        let initial_cwd = sandbox_root
            .clone()
            .unwrap_or_else(|| std::env::current_dir().unwrap_or_else(|_| PathBuf::from(".")));
        let state = ShellState::new(initial_cwd);
        Self {
            sandbox_root,
            unrestricted,
            default_env: HashMap::new(),
            state,
            permissions: CompiledPermissions::compile(&ShellPermissions::default()),
            classification_mode: ClassificationMode::default(),
            pwd_marker: new_pwd_marker(),
        }
    }

    /// Returns this tool's per-instance PWD marker. Visible to tests so they
    /// can verify cwd-recovery behaviour without depending on a hardcoded
    /// constant.
    #[doc(hidden)]
    pub fn pwd_marker(&self) -> &str {
        &self.pwd_marker
    }

    /// Set shell command permissions (allow/deny patterns).
    ///
    /// The [`ShellPermissions`] are compiled into regex patterns once and
    /// reused for every command. Invalid patterns are logged and skipped.
    pub fn with_permissions(mut self, permissions: &ShellPermissions) -> Self {
        self.permissions = CompiledPermissions::compile(permissions);
        self
    }

    /// Set the built-in risk classification mode (block/warn/off).
    ///
    /// Layers **on top of** [`Self::with_permissions`]: the permission list
    /// is the user-configurable policy (regex allow/deny), while the
    /// classifier is built-in defense-in-depth for known-destructive patterns
    /// (`rm -rf /`, `sudo`, `mkfs`, `curl|sh`, etc.).
    pub fn with_classification_mode(mut self, mode: CoreClassificationMode) -> Self {
        self.classification_mode = map_classification_mode(mode);
        self
    }

    /// Set the default working directory for commands.
    ///
    /// This replaces the persistent cwd. Useful when attaching an agent workspace.
    pub fn with_default_cwd(mut self, cwd: PathBuf) -> Self {
        if let Some(ref root) = self.sandbox_root
            && !cwd.starts_with(root)
        {
            warn!(
                default_cwd = %cwd.display(),
                sandbox_root = %root.display(),
                "default_cwd is outside sandbox_root"
            );
        }
        // Replace the state with a fresh instance rooted at the new cwd.
        // Note: this creates a new ShellState, so any in-flight background
        // tasks from the previous state will no longer be queryable.
        self.state = ShellState::new(cwd);
        self
    }

    /// Set default environment variables for spawned processes.
    ///
    /// These are injected after `env_clear()` so they don't leak the daemon's
    /// secrets. The tool call's `env` parameter overrides defaults on conflict.
    pub fn with_default_env(mut self, env: HashMap<String, String>) -> Self {
        self.default_env = env;
        self
    }

    /// Parse JSON parameters into a `ShellInput`.
    fn parse_input(&self, params: &Value) -> SandboxResult<ShellInput> {
        let command = params
            .get("command")
            .and_then(|v| v.as_str())
            .map(String::from);

        let Some(command) = command else {
            return Err(SandboxError::InvalidParameters(
                "'command' parameter is required".to_string(),
            ));
        };

        if command.trim().is_empty() {
            return Err(SandboxError::InvalidParameters(
                "'command' must not be empty".to_string(),
            ));
        }

        let description = params
            .get("description")
            .and_then(|v| v.as_str())
            .map(String::from);

        // Timeout: prefer timeout_ms, fall back to timeout_secs (deprecated)
        let timeout_ms = if let Some(ms) = params.get("timeout_ms").and_then(|v| v.as_u64()) {
            ms.min(MAX_TIMEOUT_MS)
        } else if let Some(secs) = params.get("timeout_secs").and_then(|v| v.as_u64()) {
            (secs * 1000).min(MAX_TIMEOUT_MS)
        } else {
            DEFAULT_TIMEOUT_MS
        };

        let run_in_background = params
            .get("run_in_background")
            .and_then(|v| v.as_bool())
            .unwrap_or(false);

        Ok(ShellInput {
            command,
            description,
            timeout_ms,
            run_in_background,
        })
    }

    /// Handle a request to check background task status.
    async fn handle_check_task(&self, task_id: &str) -> SandboxResult<Value> {
        match background::check_background_task(&self.state, task_id).await {
            Some(result) => {
                if let Some(ref output) = result.output {
                    Ok(serde_json::json!({
                        "task_id": result.task_id,
                        "status": "completed",
                        "command": result.command,
                        "exit_code": output.exit_code,
                        "stdout": output.stdout,
                        "stderr": output.stderr,
                    }))
                } else if let Some(ref error) = result.error {
                    Ok(serde_json::json!({
                        "task_id": result.task_id,
                        "status": "failed",
                        "command": result.command,
                        "error": error,
                    }))
                } else {
                    Ok(serde_json::json!({
                        "task_id": result.task_id,
                        "status": "unknown",
                    }))
                }
            }
            None => Ok(serde_json::json!({
                "task_id": task_id,
                "status": "not_found_or_still_running",
            })),
        }
    }
}

#[async_trait::async_trait]
impl Tool for ShellTool {
    fn name(&self) -> &str {
        SHELL_TOOL_NAME
    }

    fn description(&self) -> &str {
        "Execute a shell command (via bash -c) and return its output. \
        The working directory persists between calls. \
        Supports background execution and configurable timeouts. \
        Commands run with the daemon's filesystem access; on Linux 5.13+, \
        Landlock restricts filesystem access to the sandbox root when enabled."
    }

    fn is_builtin(&self) -> bool {
        true
    }

    fn parameters(&self) -> Value {
        serde_json::json!({
            "type": "object",
            "properties": {
                "command": {
                    "type": "string",
                    "description": "The shell command to execute (via bash -c)."
                },
                "description": {
                    "type": "string",
                    "description": "Brief description of what this command does (for audit logging)."
                },
                "timeout_ms": {
                    "type": "integer",
                    "description": "Timeout in milliseconds (default 120000, max 600000)."
                },
                "timeout_secs": {
                    "type": "number",
                    "description": "Deprecated: use timeout_ms instead. Timeout in seconds (default 120, max 600)."
                },
                "run_in_background": {
                    "type": "boolean",
                    "description": "Run the command in the background. Returns a task_id immediately.",
                    "default": false
                },
                "env": {
                    "type": "object",
                    "description": "Extra environment variables as key-value pairs.",
                    "additionalProperties": { "type": "string" }
                },
                "check_task": {
                    "type": "string",
                    "description": "Check the result of a background task by its task_id. Mutually exclusive with 'command' — when present, all other parameters are ignored."
                }
            },
            "required": []
        })
    }

    async fn execute(&self, params: Value) -> SandboxResult<Value> {
        // Special case: checking background task status
        if let Some(task_id) = params.get("check_task").and_then(|v| v.as_str()) {
            return self.handle_check_task(task_id).await;
        }

        let input = self.parse_input(&params)?;

        // Permission check: evaluate allow/deny patterns before any execution.
        // This runs before the hardcoded denylist in exec.rs (which catches
        // destructive commands like `rm -rf /`) and acts as a user-configurable
        // policy gate. On denial, surface a structured tracing event so
        // operators can filter and ship denials through the configured log
        // subscriber rather than searching scattered stderr.
        if let Err(e) = self.permissions.check_command(&input.command) {
            warn!(
                tool = "shell",
                reason = "permission_denied",
                command_excerpt = %command_excerpt(&input.command),
                error = %e,
                "Shell command blocked by permission policy"
            );
            return Err(e);
        }

        // Classification check: built-in risk detection for known destructive
        // patterns (`rm -rf /`, `sudo`, `mkfs`, `curl|sh`, reverse shells,
        // etc.). Layers with the permission system — permissions are user
        // policy, classification is built-in defense-in-depth. Hard-block
        // outcomes are logged at error level: they indicate the command
        // tripped a known-destructive heuristic.
        if let Err(e) = classification::enforce(&input.command, self.classification_mode) {
            error!(
                tool = "shell",
                reason = "classifier_denied",
                command_excerpt = %command_excerpt(&input.command),
                error = %e,
                "Shell command blocked by built-in risk classifier"
            );
            return Err(e);
        }

        // Merge tool-call env params into default_env (tool-call overrides defaults)
        let mut merged_env = self.default_env.clone();
        if let Some(env_obj) = params.get("env").and_then(|v| v.as_object()) {
            for (k, v) in env_obj {
                if security::is_secret_env_var(k) {
                    warn!(env_var = %k, "Blocked secret env var from tool-call env injection");
                    continue;
                }
                if let Some(val) = v.as_str() {
                    merged_env.insert(k.clone(), val.to_owned());
                }
            }
        }

        // Background execution
        if input.run_in_background {
            let task_id = background::submit_background_task(
                input,
                &self.state,
                self.sandbox_root.clone(),
                self.unrestricted,
                merged_env,
                self.pwd_marker.clone(),
            )
            .await?;

            return Ok(serde_json::json!({
                "task_id": task_id,
                "status": "submitted",
                "message": "Command submitted for background execution. Use check_task to retrieve results."
            }));
        }

        // Foreground execution
        let output = exec::execute_command(
            &input,
            &self.state,
            self.sandbox_root.as_deref(),
            self.unrestricted,
            &merged_env,
            &self.pwd_marker,
        )
        .await?;

        Ok(serde_json::json!({
            "exit_code": output.exit_code,
            "stdout": output.stdout,
            "stderr": output.stderr,
        }))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_shell_tool_name() {
        let tool = ShellTool::new();
        assert_eq!(tool.name(), "shell");
    }

    // ── PWD marker nonce (issue #743 item 6) ─────────────────────────────

    #[test]
    fn test_pwd_marker_is_unique_per_instance() {
        // Each freshly constructed ShellTool must have a distinct marker.
        // A stable, hardcoded constant would let a user script that prints
        // the marker corrupt cwd recovery on a different agent's instance.
        let a = ShellTool::new();
        let b = ShellTool::new();
        assert_ne!(
            a.pwd_marker(),
            b.pwd_marker(),
            "PWD markers should differ between fresh ShellTool instances"
        );
    }

    #[test]
    fn test_pwd_marker_format_has_random_suffix() {
        // The marker format is `__ALMS_PWD_<uuid_simple>__` so it remains
        // recognisable to any future tooling but uses a per-instance random
        // suffix so it cannot be guessed or accidentally collided with.
        let tool = ShellTool::new();
        let marker = tool.pwd_marker();
        assert!(marker.starts_with("__ALMS_PWD_"));
        assert!(marker.ends_with("__"));
        // The UUID simple form is 32 hex chars; with the prefix/suffix the
        // marker length is exactly 32 + 11 + 2 = 45.
        assert_eq!(marker.len(), 45);
    }

    #[test]
    fn test_pwd_marker_preserved_across_clone() {
        // Cloning a ShellTool (e.g. when registering it under both `shell`
        // and `shell_exec`) must preserve the marker so the clone recovers
        // the cwd through the same emitted token.
        let a = ShellTool::new();
        let b = a.clone();
        assert_eq!(a.pwd_marker(), b.pwd_marker());
    }

    #[test]
    fn test_pwd_marker_propagates_through_constructors() {
        // sandboxed() and with_policy() must also generate fresh markers.
        let dir = tempfile::tempdir().unwrap();
        let a = ShellTool::sandboxed(dir.path().to_path_buf());
        let b = ShellTool::with_policy(Some(dir.path().to_path_buf()), false);
        assert_ne!(a.pwd_marker(), b.pwd_marker());
        assert!(a.pwd_marker().starts_with("__ALMS_PWD_"));
        assert!(b.pwd_marker().starts_with("__ALMS_PWD_"));
    }

    #[test]
    fn test_shell_tool_description_not_empty() {
        let tool = ShellTool::new();
        assert!(!tool.description().is_empty());
    }

    #[test]
    fn test_shell_tool_is_builtin() {
        let tool = ShellTool::new();
        assert!(tool.is_builtin());
    }

    #[test]
    fn test_shell_tool_parameters_schema() {
        let tool = ShellTool::new();
        let params = tool.parameters();
        let props = params["properties"].as_object().unwrap();
        assert!(props.contains_key("command"));
        assert!(!props.contains_key("argv"), "argv mode has been removed");
        assert!(props.contains_key("description"));
        assert!(props.contains_key("timeout_ms"));
        assert!(props.contains_key("timeout_secs"));
        assert!(props.contains_key("run_in_background"));
        assert!(props.contains_key("env"));
        assert!(props.contains_key("check_task"));
        // `required` is empty at schema level: `check_task` is an alternative to
        // `command`. Runtime validation in `parse_input()` enforces `command` when
        // `check_task` is not provided.
        let required = params["required"].as_array().unwrap();
        assert!(
            required.is_empty(),
            "required should be empty — check_task is mutually exclusive with command"
        );
    }

    #[test]
    fn test_parse_input_command() {
        let tool = ShellTool::new();
        let params = serde_json::json!({"command": "ls -la"});
        let input = tool.parse_input(&params).unwrap();
        assert_eq!(input.command, "ls -la");
        assert_eq!(input.timeout_ms, DEFAULT_TIMEOUT_MS);
        assert!(!input.run_in_background);
    }

    #[test]
    fn test_parse_input_missing_command() {
        let tool = ShellTool::new();
        let params = serde_json::json!({});
        assert!(tool.parse_input(&params).is_err());
    }

    #[test]
    fn test_parse_input_empty_command() {
        let tool = ShellTool::new();
        let params = serde_json::json!({"command": "   "});
        assert!(tool.parse_input(&params).is_err());
    }

    #[test]
    fn test_parse_input_timeout_ms() {
        let tool = ShellTool::new();
        let params = serde_json::json!({"command": "ls", "timeout_ms": 5000});
        let input = tool.parse_input(&params).unwrap();
        assert_eq!(input.timeout_ms, 5000);
    }

    #[test]
    fn test_parse_input_timeout_secs_fallback() {
        let tool = ShellTool::new();
        let params = serde_json::json!({"command": "ls", "timeout_secs": 60});
        let input = tool.parse_input(&params).unwrap();
        assert_eq!(input.timeout_ms, 60_000);
    }

    #[test]
    fn test_parse_input_timeout_clamped() {
        let tool = ShellTool::new();
        let params = serde_json::json!({"command": "ls", "timeout_ms": 9_999_999});
        let input = tool.parse_input(&params).unwrap();
        assert_eq!(input.timeout_ms, MAX_TIMEOUT_MS);
    }

    #[test]
    fn test_parse_input_background() {
        let tool = ShellTool::new();
        let params = serde_json::json!({"command": "sleep 10", "run_in_background": true});
        let input = tool.parse_input(&params).unwrap();
        assert!(input.run_in_background);
    }

    #[test]
    fn test_parse_input_description() {
        let tool = ShellTool::new();
        let params = serde_json::json!({"command": "ls", "description": "List files"});
        let input = tool.parse_input(&params).unwrap();
        assert_eq!(input.description.as_deref(), Some("List files"));
    }

    // ── Integration tests (Unix only) ─────────────────────────────────────

    #[tokio::test]
    #[cfg(unix)]
    async fn test_shell_tool_command_echo() {
        let tool = ShellTool::new();
        let result = tool
            .execute(serde_json::json!({"command": "echo hello"}))
            .await
            .unwrap();
        assert_eq!(result["exit_code"], 0);
        assert!(result["stdout"].as_str().unwrap().contains("hello"));
    }

    #[tokio::test]
    #[cfg(unix)]
    async fn test_shell_tool_persistent_cwd() {
        let tool = ShellTool::new();

        // Change directory
        let result = tool
            .execute(serde_json::json!({"command": "cd /tmp && pwd"}))
            .await
            .unwrap();
        assert_eq!(result["exit_code"], 0);
        assert!(result["stdout"].as_str().unwrap().contains("/tmp"));

        // Next command should start in /tmp
        let result = tool
            .execute(serde_json::json!({"command": "pwd"}))
            .await
            .unwrap();
        assert_eq!(result["exit_code"], 0);
        assert!(result["stdout"].as_str().unwrap().contains("/tmp"));
    }

    #[tokio::test]
    #[cfg(unix)]
    async fn test_shell_tool_env_cleared() {
        let tool = ShellTool::new();
        let result = tool
            .execute(serde_json::json!({"command": "env"}))
            .await
            .unwrap();
        let stdout = result["stdout"].as_str().unwrap();
        assert!(
            !stdout.contains("OPENROUTER_API_KEY"),
            "API keys must not leak into spawned processes"
        );
        assert!(
            stdout.contains("PATH="),
            "PATH should be re-injected after env_clear()"
        );
    }

    #[tokio::test]
    #[cfg(unix)]
    async fn test_shell_tool_default_env() {
        let mut env = HashMap::new();
        env.insert("ALMS_DATA_DIR".to_string(), "/tmp/alms-test".to_string());
        let tool = ShellTool::new().with_default_env(env);

        let result = tool
            .execute(serde_json::json!({"command": "env"}))
            .await
            .unwrap();
        let stdout = result["stdout"].as_str().unwrap();
        assert!(stdout.contains("ALMS_DATA_DIR=/tmp/alms-test"));
    }

    #[tokio::test]
    #[cfg(unix)]
    async fn test_shell_tool_env_override() {
        let mut env = HashMap::new();
        env.insert("ALMS_DATA_DIR".to_string(), "/default".to_string());
        let tool = ShellTool::new().with_default_env(env);

        let result = tool
            .execute(serde_json::json!({
                "command": "env",
                "env": {"ALMS_DATA_DIR": "/override"}
            }))
            .await
            .unwrap();
        let stdout = result["stdout"].as_str().unwrap();
        assert!(stdout.contains("ALMS_DATA_DIR=/override"));
        assert!(!stdout.contains("ALMS_DATA_DIR=/default"));
    }

    #[tokio::test]
    #[cfg(unix)]
    async fn test_shell_tool_blocks_secret_env() {
        let tool = ShellTool::new();
        let result = tool
            .execute(serde_json::json!({
                "command": "env",
                "env": {"OPENAI_API_KEY": "stolen", "SAFE_VAR": "ok"}
            }))
            .await
            .unwrap();
        let stdout = result["stdout"].as_str().unwrap();
        assert!(!stdout.contains("OPENAI_API_KEY"));
        assert!(stdout.contains("SAFE_VAR=ok"));
    }

    /// Regression guard for #744: the hardcoded denied-filename substring
    /// check was removed because a single-entry list (`secrets.json`) was
    /// not user-configurable, did not scale, and was trivially bypassable.
    /// Users who need file-level protection should use
    /// `[tools.shell_permissions]` (configurable regex allow/deny) or
    /// Landlock (kernel-level path enforcement on Linux).
    ///
    /// This test documents that the removed policy no longer fires: a
    /// shell command mentioning `secrets.json` is no longer blocked at
    /// the shell-tool layer for that reason alone. (The command itself
    /// may still fail for unrelated reasons — missing file, permissions,
    /// etc. — so we only assert that it is *not* blocked with the legacy
    /// "denied file" message.)
    #[tokio::test]
    #[cfg(unix)]
    async fn test_shell_tool_no_hardcoded_denied_filename() {
        let tool = ShellTool::new();
        let result = tool
            .execute(serde_json::json!({"command": "echo secrets.json"}))
            .await;
        // Must succeed now: the hardcoded denied-filename check is gone.
        // `echo` does not touch the filesystem and has no reason to fail.
        let ok = result.expect("echo of a string should not be blocked");
        assert_eq!(ok["exit_code"], 0);
    }

    #[tokio::test]
    #[cfg(unix)]
    async fn test_shell_tool_denied_pattern() {
        // With the classifier in place, `rm -rf /` is now blocked by the
        // built-in risk classifier before the legacy denylist ever fires.
        // The user-facing error reveals only the level, not the heuristic.
        let tool = ShellTool::new();
        let result = tool
            .execute(serde_json::json!({"command": "rm -rf /"}))
            .await;
        assert!(result.is_err());
        let err = result.unwrap_err().to_string();
        assert!(
            err.contains("blocked") || err.contains("denied"),
            "expected blocked-or-denied message, got: {err}"
        );
    }

    #[tokio::test]
    #[cfg(unix)]
    async fn test_shell_tool_sandboxed_cwd_stays_inside() {
        let dir = tempfile::tempdir().unwrap();
        let root = std::fs::canonicalize(dir.path()).unwrap();
        let tool = ShellTool::sandboxed(root.clone());

        // The command changes to /etc in a subshell, but the persistent cwd
        // should NOT be updated to /etc because it is outside the sandbox root.
        let result = tool
            .execute(serde_json::json!({"command": "cd /etc && ls"}))
            .await;
        // The command itself should succeed (it runs in a subshell)
        assert!(result.is_ok(), "command should execute successfully");

        // Verify the persistent cwd is still inside the sandbox root
        let cwd_result = tool
            .execute(serde_json::json!({"command": "pwd"}))
            .await
            .unwrap();
        let stdout = cwd_result["stdout"].as_str().unwrap();
        let cwd_path = std::path::Path::new(stdout.trim());
        assert!(
            std::fs::canonicalize(cwd_path)
                .unwrap_or_default()
                .starts_with(&root),
            "persistent cwd '{}' should remain inside sandbox root '{}'",
            stdout.trim(),
            root.display()
        );
    }

    #[tokio::test]
    #[cfg(unix)]
    async fn test_shell_tool_background_execution() {
        let tool = ShellTool::new();

        // Submit background task
        let result = tool
            .execute(serde_json::json!({
                "command": "echo background_test",
                "run_in_background": true
            }))
            .await
            .unwrap();
        assert_eq!(result["status"], "submitted");
        let task_id = result["task_id"].as_str().unwrap();

        // Wait for completion
        tokio::time::sleep(std::time::Duration::from_millis(500)).await;

        // Check task result
        let result = tool
            .execute(serde_json::json!({"check_task": task_id}))
            .await
            .unwrap();
        assert_eq!(result["status"], "completed");
        assert!(
            result["stdout"]
                .as_str()
                .unwrap()
                .contains("background_test")
        );
    }

    #[tokio::test]
    async fn test_shell_tool_missing_command() {
        let tool = ShellTool::new();
        let result = tool.execute(serde_json::json!({})).await;
        assert!(result.is_err());
    }

    #[tokio::test]
    async fn test_shell_tool_argv_rejected() {
        // argv mode has been removed; passing argv without command should fail
        let tool = ShellTool::new();
        let result = tool
            .execute(serde_json::json!({"argv": ["echo", "hello"]}))
            .await;
        assert!(result.is_err());
    }

    #[tokio::test]
    #[cfg(unix)]
    async fn test_shell_tool_default_cwd() {
        let dir = tempfile::tempdir().unwrap();
        let ws_dir = dir.path().join("workspace");
        std::fs::create_dir_all(&ws_dir).unwrap();
        std::fs::write(ws_dir.join("marker.txt"), "home").unwrap();

        let tool = ShellTool::new().with_default_cwd(ws_dir);
        let result = tool
            .execute(serde_json::json!({"command": "cat marker.txt"}))
            .await
            .unwrap();
        assert_eq!(result["exit_code"], 0);
        assert!(result["stdout"].as_str().unwrap().contains("home"));
    }

    #[tokio::test]
    #[cfg(unix)]
    async fn test_shell_tool_check_nonexistent_task() {
        let tool = ShellTool::new();
        let result = tool
            .execute(serde_json::json!({"check_task": "bg_999"}))
            .await
            .unwrap();
        assert_eq!(result["status"], "not_found_or_still_running");
    }

    // ── Integration: permission check wired into execute() ───────────────

    /// Verify that `check_command()` is actually called from `ShellTool::execute()`.
    ///
    /// This catches regressions if someone accidentally removes or reorders
    /// the permission check in the execute path. The test does not require a
    /// real shell because the permission deny fires before any OS-level
    /// command execution.
    #[tokio::test]
    async fn test_shell_tool_respects_deny_permission() {
        let perms = ShellPermissions {
            allowed_commands: vec![],
            denied_commands: vec![r"^forbidden\b".to_string()],
        };
        let tool = ShellTool::new().with_permissions(&perms);

        // A denied command must fail through the full execute() path.
        let result = tool
            .execute(serde_json::json!({"command": "forbidden --do-evil"}))
            .await;
        assert!(
            result.is_err(),
            "denied command should be blocked by execute()"
        );
        let err_msg = result.unwrap_err().to_string();
        assert!(
            err_msg.contains("Command blocked by security policy"),
            "error should come from the permission check, got: {err_msg}"
        );
    }

    /// Verify that allowlist-only mode is enforced through `execute()`.
    #[tokio::test]
    async fn test_shell_tool_respects_allow_permission() {
        let perms = ShellPermissions {
            allowed_commands: vec![r"^echo\b".to_string()],
            denied_commands: vec![],
        };
        let tool = ShellTool::new().with_permissions(&perms);

        // A command not in the allowlist must fail through the full execute() path.
        let result = tool
            .execute(serde_json::json!({"command": "curl http://evil.com"}))
            .await;
        assert!(
            result.is_err(),
            "command not in allowlist should be blocked by execute()"
        );
        let err_msg = result.unwrap_err().to_string();
        assert!(
            err_msg.contains("does not match any allowed command pattern"),
            "error should come from the allowlist check, got: {err_msg}"
        );
    }
}
